import type { Category, Opportunity } from "./types";

// Counts reflect live WordPress category totals on www.onlinelearnership.co.za
export const categories: Category[] = [
  {
    slug: "learnerships",
    name: "Learnerships",
    description: "NQF accredited training programmes with a stipend.",
    icon: "GraduationCap",
    count: 316,
    accent: "brand",
  },
  {
    slug: "internships",
    name: "Internships",
    description: "Workplace experience for graduates and students.",
    icon: "Briefcase",
    count: 130,
    accent: "accent",
  },
  {
    slug: "bursaries",
    name: "Bursaries",
    description: "Full and partial funding to study in South Africa.",
    icon: "Wallet",
    count: 39,
    accent: "warm",
  },
  {
    slug: "apprenticeships",
    name: "Apprenticeships",
    description: "Earn a trade qualification while you work.",
    icon: "Wrench",
    count: 25,
    accent: "rose",
  },
  {
    slug: "government",
    name: "Government Jobs",
    description: "Public sector vacancies and government opportunities.",
    icon: "Building2",
    count: 29,
    accent: "sky",
  },
  {
    slug: "training",
    name: "Training Programmes",
    description: "Skill-building courses and short programmes.",
    icon: "Award",
    count: 99,
    accent: "purple",
  },
];

export const sectors = [
  "Agriculture",
  "Banking & Finance",
  "Engineering",
  "Healthcare",
  "Information Technology",
  "Insurance",
  "Logistics & Supply Chain",
  "Mining",
  "Retail",
  "Telecommunications",
  "Tourism & Hospitality",
  "Education",
];

export const opportunities: Opportunity[] = [
  {
    slug: "sasol-engineering-learnership-2026",
    title: "Sasol Engineering Learnership 2026",
    organisation: "Sasol",
    type: "learnership",
    category: "Engineering",
    location: "Mpumalanga",
    stipend: "R 6 500 / month",
    duration: "12 months",
    closingDate: "2026-07-31",
    postedDate: "2026-06-02",
    minQualification: "Grade 12 / Matric",
    description:
      "Sasol is offering 80 NQF Level 3 engineering learnerships at its Secunda operations. The programme combines structured workplace experience with theoretical classroom learning, leading to a recognised qualification and a strong pipeline into permanent technical roles.",
    requirements: [
      "South African citizen aged 18–35",
      "Grade 12 with Mathematics (not Maths Literacy) at level 4 (50%) or higher",
      "Physical Science at level 4 (50%) or higher",
      "Currently unemployed and not studying full-time",
      "Medically fit for an industrial environment",
    ],
    responsibilities: [
      "Attend classroom-based theoretical training at an accredited provider",
      "Complete on-the-job experiential learning at Sasol Secunda",
      "Submit a portfolio of evidence assessed against unit standards",
      "Adhere to all Sasol safety, health and environment standards",
    ],
    howToApply: [
      "Click Apply Now to open the Sasol careers portal",
      "Create a profile and upload your ID, Matric certificate, and CV",
      "Complete the online numerical and mechanical reasoning assessment",
      "Shortlisted candidates are invited to a medical and panel interview",
    ],
    applyUrl: "https://www.sasol.com/careers",
    featured: true,
    tags: ["NQF 3", "Stipend", "Permanent pipeline"],
  },
  {
    slug: "absa-graduate-programme-2026",
    title: "Absa Graduate Programme 2026 — Investment Banking",
    organisation: "Absa",
    type: "graduate",
    category: "Banking & Finance",
    location: "Gauteng",
    stipend: "Market related",
    duration: "24 months",
    closingDate: "2026-08-15",
    postedDate: "2026-05-28",
    minQualification: "Degree",
    description:
      "Absa's flagship Graduate Programme rotates top graduates through Corporate Finance, Markets, and Private Banking over 24 months, with international placement opportunities and mentorship from senior leaders.",
    requirements: [
      "Honours degree (or final-year student) in BCom, BBusSci, Engineering or related",
      "Minimum 65% academic average",
      "South African citizen",
      "Strong analytical and communication skills",
      "Leadership experience through clubs, sport or community work",
    ],
    responsibilities: [
      "Rotate through three business units over 24 months",
      "Contribute to live client deals under senior banker guidance",
      "Complete the CFA Level 1 examination (sponsored)",
      "Present a capstone strategy project to the executive committee",
    ],
    howToApply: [
      "Apply via the Absa Graduate portal",
      "Complete cognitive and situational judgement assessments",
      "Attend a virtual assessment centre",
      "Final panel interview with business heads",
    ],
    applyUrl: "https://absa.co.za/graduates",
    featured: true,
    tags: ["Rotational", "CFA sponsored", "International"],
  },
  {
    slug: "nsfas-bursary-2027",
    title: "NSFAS Bursary 2027 — Now open for applications",
    organisation: "NSFAS",
    type: "bursary",
    category: "Education",
    location: "Nationwide",
    duration: "Full degree / diploma",
    closingDate: "2026-11-30",
    postedDate: "2026-06-01",
    minQualification: "Grade 12 / Matric",
    description:
      "The National Student Financial Aid Scheme funds tuition, accommodation, meals, books, and a learning materials allowance for qualifying students at all 26 public universities and 50 TVET colleges in South Africa.",
    requirements: [
      "South African citizen",
      "Combined household income below R 350 000 per year (R 600 000 for SASSA recipients with a disability)",
      "Accepted or applying to a public university or TVET college",
      "Meet the academic admission requirements of your chosen programme",
    ],
    responsibilities: [
      "Maintain a minimum 50% pass rate per academic year",
      "Submit progress reports each semester",
      "Reapply annually for continued funding",
    ],
    howToApply: [
      "Visit my.nsfas.org.za and create a myNSFAS account",
      "Upload your ID, parents' IDs, proof of income, and Grade 12 results",
      "Submit the consent form for ITC and SARS verification",
      "Track your application status via the myNSFAS portal",
    ],
    applyUrl: "https://www.nsfas.org.za",
    featured: true,
    tags: ["Full funding", "Universities", "TVET colleges"],
  },
  {
    slug: "transnet-apprenticeship-2026",
    title: "Transnet Artisan Apprenticeship 2026",
    organisation: "Transnet",
    type: "apprenticeship",
    category: "Engineering",
    location: "KwaZulu-Natal",
    stipend: "R 5 800 / month",
    duration: "36 months",
    closingDate: "2026-07-10",
    postedDate: "2026-05-20",
    minQualification: "Grade 12 / Matric",
    description:
      "Transnet is recruiting 120 apprentices into Diesel Mechanic, Electrician, Fitter, and Boilermaker trades at its Durban and Richards Bay operations. Successful apprentices qualify as Red Seal artisans.",
    requirements: [
      "Grade 12 with Mathematics and Physical Science (each at level 4 or higher)",
      "N2 Engineering Studies with four relevant trade subjects, or",
      "N3 / NCV Level 4 in an engineering field",
      "South African citizen aged 18–35",
    ],
    responsibilities: [
      "Complete the structured 36-month apprenticeship plan",
      "Attend block-release theoretical training",
      "Pass the QCTO trade test to qualify as a Red Seal artisan",
    ],
    howToApply: [
      "Apply at careers.transnet.net",
      "Reference: TFR/APP/2026/0119",
    ],
    applyUrl: "https://careers.transnet.net",
    tags: ["Red Seal", "Diesel Mechanic", "Boilermaker"],
  },
  {
    slug: "shoprite-yes-internship-2026",
    title: "Shoprite YES Internship 2026 — 1 000 placements",
    organisation: "Shoprite Holdings",
    type: "internship",
    category: "Retail",
    location: "Nationwide",
    stipend: "R 4 500 / month",
    duration: "12 months",
    closingDate: "2026-06-30",
    postedDate: "2026-05-15",
    minQualification: "Grade 12 / Matric",
    description:
      "Shoprite is partnering with the Presidential Youth Employment Initiative (YES) to place 1 000 unemployed youth into retail operations roles across South Africa. Top performers are offered permanent employment.",
    requirements: [
      "Unemployed South African aged 18–28",
      "Grade 12 / Matric",
      "Willingness to work shifts including weekends",
      "Live within 25km of a participating store",
    ],
    responsibilities: [
      "Customer service and till operations",
      "Stock receiving and merchandising",
      "Hygiene and food safety compliance",
    ],
    howToApply: [
      "Apply via Shoprite.jobs YES portal",
      "Bring ID, Matric certificate and proof of address to the store interview",
    ],
    applyUrl: "https://www.shoprite.jobs",
    tags: ["YES4Youth", "Permanent pipeline"],
  },
  {
    slug: "dpsa-circular-22-2026",
    title: "DPSA Circular 22 of 2026 — 312 government vacancies",
    organisation: "Department of Public Service & Administration",
    type: "government",
    category: "Government",
    location: "Nationwide",
    closingDate: "2026-06-20",
    postedDate: "2026-06-03",
    minQualification: "Grade 12 / Matric",
    description:
      "The latest DPSA circular lists 312 vacancies across national and provincial departments — from administrative clerks (salary level 5) to senior management positions. Each post lists its own closing date and Z83 reference.",
    requirements: [
      "Complete the new Z83 application form (mandatory since 1 January 2021)",
      "Attach a CV with three contactable references",
      "Certified copies are only required from shortlisted candidates",
    ],
    responsibilities: [
      "Each position has its own duty list — see the linked circular PDF",
    ],
    howToApply: [
      "Download Circular 22 of 2026 from dpsa.gov.za",
      "Identify the post(s) you qualify for and follow each department's submission instructions",
    ],
    applyUrl: "https://www.dpsa.gov.za/circulars",
    tags: ["Z83", "Salary Levels 5-12", "Multiple departments"],
  },
  {
    slug: "discovery-it-internship-2026",
    title: "Discovery IT Internship 2026 — Cloud & Data",
    organisation: "Discovery",
    type: "internship",
    category: "Information Technology",
    location: "Gauteng",
    stipend: "R 12 000 / month",
    duration: "12 months",
    closingDate: "2026-07-15",
    postedDate: "2026-05-30",
    minQualification: "Diploma",
    description:
      "Discovery is placing 40 interns into its Cloud Platform, Data Engineering, and Cybersecurity teams. Interns receive AWS, Azure, and Databricks certifications fully sponsored.",
    requirements: [
      "BSc / BCom / Diploma in Computer Science, Information Systems or related",
      "Strong fundamentals in SQL and at least one programming language",
      "Curiosity, problem-solving, and a portfolio of personal projects",
    ],
    responsibilities: [
      "Pair-program with senior engineers on production systems",
      "Complete two AWS and one Azure certification",
      "Present a hackathon project to the CTO",
    ],
    howToApply: ["Apply at discovery.co.za/careers", "Complete the HackerRank screening assessment"],
    applyUrl: "https://www.discovery.co.za/careers",
    featured: true,
    tags: ["AWS certified", "R12k stipend", "Permanent track"],
  },
  {
    slug: "mtn-bursary-2027",
    title: "MTN Foundation Bursary 2027 — ICT & Engineering",
    organisation: "MTN Foundation",
    type: "bursary",
    category: "Information Technology",
    location: "Nationwide",
    duration: "Full degree (4 years)",
    closingDate: "2026-09-30",
    postedDate: "2026-05-25",
    minQualification: "Grade 12 / Matric",
    description:
      "The MTN Foundation offers 50 full bursaries to first-year students pursuing degrees in Computer Science, Electrical Engineering, Data Science, and Cybersecurity at South African universities.",
    requirements: [
      "Grade 12 with at least 75% in Mathematics",
      "Combined household income below R 600 000 per annum",
      "Accepted into an eligible degree at a public SA university",
    ],
    responsibilities: [
      "Maintain a 65% academic average",
      "Complete annual MTN vacation work",
      "Mentor a Grade 11 learner from your home community",
    ],
    howToApply: ["Apply at mtn.com/foundation/bursaries"],
    applyUrl: "https://www.mtn.com",
    tags: ["Full funding", "Vacation work", "Mentorship"],
  },
  {
    slug: "sars-tax-learnership-2026",
    title: "SARS Tax Learnership 2026 — NQF Level 6",
    organisation: "South African Revenue Service",
    type: "learnership",
    category: "Banking & Finance",
    location: "Gauteng",
    stipend: "R 9 200 / month",
    duration: "18 months",
    closingDate: "2026-07-05",
    postedDate: "2026-05-18",
    minQualification: "Degree",
    description:
      "SARS is recruiting 200 graduates into its NQF Level 6 Tax Technician learnership. The programme leads to a SAIT-recognised qualification and a strong pathway into a permanent tax specialist role.",
    requirements: [
      "BCom / BCompt / Diploma majoring in Taxation, Accounting or Auditing",
      "Average of 60% in tax and accounting modules",
      "South African citizen aged 18–35",
    ],
    responsibilities: [
      "Complete the SAIT Tax Technician qualification",
      "Work on real audits and tax assessments",
      "Pass the QCTO summative assessment",
    ],
    howToApply: ["Apply via the SARS e-Recruitment portal"],
    applyUrl: "https://www.sars.gov.za/careers",
    tags: ["SAIT accredited", "R9 200 stipend"],
  },
  {
    slug: "eskom-bursary-2027",
    title: "Eskom Bursary 2027 — Engineering & Trades",
    organisation: "Eskom",
    type: "bursary",
    category: "Engineering",
    location: "Nationwide",
    duration: "Full qualification",
    closingDate: "2026-08-31",
    postedDate: "2026-05-22",
    minQualification: "Grade 12 / Matric",
    description:
      "Eskom funds engineering bursars across all disciplines — Electrical, Mechanical, Civil, Industrial, Mining, Metallurgical and Chemical — including tuition, residence, books, laptop, and a monthly meal allowance.",
    requirements: [
      "Grade 12 with Mathematics 70%+ and Physical Science 60%+",
      "South African citizen",
      "Accepted to a recognised SA university engineering programme",
    ],
    responsibilities: [
      "Maintain a 60% academic average",
      "Complete annual vacation work at an Eskom site",
      "Sign a year-for-year work-back agreement with Eskom on graduation",
    ],
    howToApply: ["Apply at eskom.co.za/bursaries"],
    applyUrl: "https://www.eskom.co.za",
    tags: ["Full bursary", "Laptop included", "Work-back agreement"],
  },
  {
    slug: "old-mutual-actuarial-graduate-2026",
    title: "Old Mutual Actuarial Graduate Programme 2026",
    organisation: "Old Mutual",
    type: "graduate",
    category: "Insurance",
    location: "Western Cape",
    stipend: "Market related",
    duration: "36 months",
    closingDate: "2026-08-01",
    postedDate: "2026-05-12",
    minQualification: "Degree",
    description:
      "Old Mutual's actuarial graduate programme rotates trainees through Life, Investments, and Risk over 36 months while fully funding the path to qualification as a Fellow of the Actuarial Society of South Africa (FASSA).",
    requirements: [
      "Honours in Actuarial Science with at least three A1/A2 exemptions",
      "South African citizen or permanent resident",
    ],
    responsibilities: [
      "Rotate through three actuarial business units",
      "Pass A2, A3, F1, F2 examinations within the programme period",
    ],
    howToApply: ["Apply at oldmutual.co.za/graduates"],
    applyUrl: "https://www.oldmutual.co.za",
    tags: ["FASSA pathway", "3 rotations", "Study leave"],
  },
  {
    slug: "netcare-nursing-learnership-2026",
    title: "Netcare Nursing Learnership 2026 — 350 places",
    organisation: "Netcare Education",
    type: "learnership",
    category: "Healthcare",
    location: "Nationwide",
    stipend: "R 4 200 / month + accommodation",
    duration: "12 months",
    closingDate: "2026-06-25",
    postedDate: "2026-05-10",
    minQualification: "Grade 12 / Matric",
    description:
      "Netcare Education is offering 350 places on the Higher Certificate in Auxiliary Nursing learnership across its training campuses in Gauteng, KZN and the Western Cape.",
    requirements: [
      "Grade 12 with English level 4 and Life Sciences level 4",
      "South African citizen aged 18–35",
      "Medically fit and willing to work shifts",
    ],
    responsibilities: [
      "Complete the SANC-registered Higher Certificate in Auxiliary Nursing",
      "Rotate through medical, surgical and casualty wards",
    ],
    howToApply: ["Apply at netcare.co.za/education"],
    applyUrl: "https://www.netcare.co.za",
    featured: true,
    tags: ["SANC accredited", "Accommodation included"],
  },
];

// Conservative figures sourced from live WordPress category counts.
export const stats = [
  { label: "Live opportunities", value: "640+" },
  { label: "Updated", value: "Daily" },
  { label: "Cost to apply", value: "R0" },
  { label: "Trusted source", value: "Verified" },
];

export function getOpportunityBySlug(slug: string): Opportunity | undefined {
  return opportunities.find((o) => o.slug === slug);
}

export function getRelatedOpportunities(slug: string, limit = 3): Opportunity[] {
  const current = getOpportunityBySlug(slug);
  if (!current) return [];
  return opportunities
    .filter((o) => o.slug !== slug && (o.category === current.category || o.type === current.type))
    .slice(0, limit);
}
